### PR TITLE
fix: regression in `Version::starts_with`

### LINKED ISSUE #1914: Unsolvable environment with `py-rattler>=0.17`; works with `<=0.16`
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

`py-rattler==0.17` breaks the [`tests/core/test_solve.py::test_freeze_deps_1`](https://github.com/conda/conda/blob/24c70a60ff017b99accdb6b034d27fa0346dad82/tests/core/test_solve.py#L3060) test in `conda/conda`.

I've put a reproducer with these two files:

- [`rattlonda.py`](https://gist.github.com/jaimergp/5b59209ba77b60e01f29d19178231064) is a simple conda environment creator that only uses rattler. I use it for debugging only and yes, don't know what to think of that name.
- The attached [repodata.json.zip](https://github.com/user-attachments/files/24031816/repodata.json.zip) is taken from `conda`'s `index2.json`. All kinds of funky from last decade.

Steps:

1. Unpack the zipped `repodata.json` somewhere under a `noarch` directory; e.g. `~/tmp/freeze-deps-issue/noarch`
2. Run this: 

```bash
# Works
$ uv run --with py-rattler==0.16 https://gist.github.com/jaimergp/5b59209ba77b60e01f29d19178231064/raw/e592645c522b1874078e38007f747f57e7ea0152/rattlonda.py -d -c ~/tmp/freeze-deps-issue six=1.7
started solving the environment
solved required dependencies
six=1.7.3=py34_0
python=3.4.5=0
tk=8.5.18=0
sqlite=3.13.0=0
openssl=1.0.2l=0
readline=6.2=2
xz=5.2.3=0
zlib=1.2.11=0
created environment: None
```
```bash
# Fails
$ uv run --with py-rattler==0.17 https://gist.github.com/jaimergp/5b59209ba77b60e01f29d19178231064/raw/e592645c522b1874078e38007f747f57e7ea0152/rattlonda.py -d -c ~/tmp/freeze-deps-issue six=1.7
exceptions.SolverException: Cannot solve the request because of: six 1.7.* cannot be installed because there are no viable options:
├─ six 1.7.2 | 1.7.3 would require
│  └─ python 3.4.*, which cannot be installed because there are no viable options:
│     └─ python 3.4.0 | 3.4.1 | 3.4.1 | 3.4.1 | 3.4.1 | 3.4.1 | 3.4.2 | 3.4.3 | 3.4.3 | 3.4.3 | 3.4.4 | 3.4.4 | 3.4.5 would require
│        └─ openssl 1.0.1.*, for which no candidates were found.
├─ six 1.7.2 | 1.7.3 would require
│  └─ python 3.3.*, which cannot be installed because there are no viable options:
│     └─ python 3.3.0 | 3.3.0 | 3.3.0 | 3.3.1 | 3.3.2 | 3.3.2 | 3.3.3 | 3.3.4 | 3.3.5 | 3.3.5 | 3.3.5 | 3.3.5 | 3.3.5 would require
│        └─ openssl 1.0.1.*, for which no candidates were found.
├─ six 1.7.2 | 1.7.3 would require
│  └─ python 2.7.*, which cannot be installed because there are no viable options:
│     └─ python 2.7.3 | 2.7.3 | 2.7.3 | 2.7.3 | 2.7.3 | 2.7.3 | 2.7.4 | 2.7.5 | 2.7.5 | 2.7.5 | 2.7.5 | 2.7.6 | 2.7.6 | 2.7.6 | 2.7.7 | 2.7.7 | 2.7.8 | 2.7.8 | 2.7.9 | 2.7.9 | 2.7.9 | 2.7.9 | 2.7.9 | 2.7.9 | 2.7.10 | 2.7.10 | 2.7.10 | 2.7.10 | 2.7.11 | 2.7.11 | 2.7.11 | 2.7.12 | 2.7.12 | 2.7.13 would require
│        └─ openssl 1.0.1.*, for which no candidates were found.
└─ six 1.7.2 | 1.7.3 would require
   └─ python 2.6.*, which cannot be installed because there are no viable options:
      └─ python 2.6.8 | 2.6.8 | 2.6.8 | 2.6.8 | 2.6.8 | 2.6.8 | 2.6.8 | 2.6.9 | 2.6.9 would require
         └─ openssl 1.0.1.*, for which no candidates were found.
```

You can try other versions; the breaking release is 0.17. 0.18 fails; 0.16 and earlier succeed.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by baszalmstra**
#1914 highlighted a regression in our `Version::starts_with` implementation introduced by https://github.com/conda/rattler/pull/1791 . This PR fixes this issue. Added extensive tests to verify both cases.

@jaimergp I will include this in the python release.

Fixes #1914

### CODE REVIEW

File: crates/rattler_conda_types/src/version/mod.rs [hunk 1]
```diff
@@ -1289,17 +1306,90 @@ mod test {
...
+        // This is a structure mismatch, not just extra components at the end
+        assert!(!Version::from_str("1.1c.1")
+            .unwrap()
+            .starts_with(&Version::from_str("1.1.1").unwrap()));
+        assert!(!Version::from_str("1.1c1.1")
+            .unwrap()
+            .starts_with(&Version::from_str("1.1c.1").unwrap()));
+
+        // BUT zero components in prefix are treated as "no component" (implicit zeros)
+        // So "1.1c.1" starts with "1.1c0.1" because c0 == c (trailing zero)
```
Comment (wolfv) [inline crates/rattler_conda_types/src/version/mod.rs:1368]: This one is a bit surprising but I am fine with it. Did you double check vs. Conda?

Comment (baszalmstra) [reply crates/rattler_conda_types/src/version/mod.rs:1368]:
```python
In [5]: VersionSpec("1.1c0.1*").match("1.1c.1")
Out[5]: True
```

Comment (baszalmstra) [reply crates/rattler_conda_types/src/version/mod.rs:1368]: I just tried this will all the test cases in that test and conda reports the same values.

Comment (wolfv) [reply crates/rattler_conda_types/src/version/mod.rs:1368]: Awesome. The code is the spec 🚀

Comment (baszalmstra) [reply crates/rattler_conda_types/src/version/mod.rs:1368]: Yeah I really have to start reading and commenting on the CEP that covers this...
