### PR TITLE
fix: StrictVersion Ord contract violation

### LINKED ISSUE #2224: StrictVersion violates Rust's Ord contract — silent BTreeMap/BTreeSet corruption
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

StrictVersion derives Ord and PartialOrd (delegating to Version::Ord) but manually implements PartialEq with  strict equality. This creates a direct violation of Rust's Ord contract: "a.cmp(b) == Equal if and only if a == b".                                                                                                        
                                                                                                              
  ### Reproduction

```rust
  use rattler_conda_types::version::StrictVersion;
  use std::str::FromStr;                                                                                        
  use std::cmp::Ordering;                                                                                       
                                                                                                                
  let a = StrictVersion::from_str("1.0").unwrap();                                                              
  let b = StrictVersion::from_str("1.0.0").unwrap();                                                            
                                                                                                                
  assert_ne!(a, b);                           // PartialEq says different                                     
  assert_eq!(a.cmp(&b), Ordering::Equal);     // Ord says equal — CONTRACT VIOLATION          
```               
                                                                                                                
  Version::Ord collapses trailing zeros ("1.0" == "1.0.0" semantically). StrictVersion::PartialEq checks raw    
  component counts first, so "1.0" != "1.0.0". The derived Ord never applies this stricter check.               
                                                                                                                
  ### Impact                                                                                                        
  
  - BTreeMap<StrictVersion, _> and BTreeSet<StrictVersion> silently lose entries or fail lookups — inserting    
  "1.0" and "1.0.0" as keys may overwrite each other                                                          
  - sort() + dedup() on Vec<StrictVersion> collapses distinct entries                                           
  - VersionSpec (which derives Ord and contains a StrictRange(StrictRangeOperator, StrictVersion) variant)      
  inherits the broken ordering, propagating the corruption into the solver's dependency structures              
                                                                                                                

@baszalmstra 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ritankarsaha**
### Problem                                                                                                       
  
  StrictVersion derived Ord and PartialOrd, delegating to Version::Ord. Version::Ord collapses trailing zeros —  so "1.0".cmp("1.0.0") == Ordering::Equal. But StrictVersion::PartialEq is manually implemented and checks raw component counts first, making "1.0" != "1.0.0".                                                              
                                                                                                              
  This violates Rust's Ord contract: a.cmp(b) == Equal if and only if a == b.                                   
  
  ### Consequences:                                                                                                 
  - BTreeMap<StrictVersion, _> and BTreeSet<StrictVersion> silently lose entries ("1.0" and "1.0.0" as keys may
  collide)                                                                                                      
  - sort() + dedup() on Vec<StrictVersion> collapses distinct versions
  - VersionSpec (which derives Ord and has a StrictRange(_, StrictVersion) variant) inherits the broken         
  invariant                                                                                                     

The existing strict_version_test even asserted the broken behavior (assert_eq!(v_1_0.cmp(&v_1_0_0), Ordering::Equal)).   

Fixes #2224 

### How Has This Been Tested?

- Updated strict_version_test, replaced the assertion of the broken behavior with the correct expected       
  ordering                                                                                                      
  - Added strict_version_ord_contract which verifies cmp != Equal for unequal values, antisymmetry, BTreeSet        
  correctness (both entries survive), and sort+dedup correctness                                                
  - Added strict_version_ord_with_genuine_differences that verifies that semantically ordered versions ("1.0" < 
  "2.0", etc.) still order correctly after the fix.

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added sufficient tests to cover my changes.

### CODE REVIEW

**Comment by ritankarsaha** [comment]
@baszalmstra fixed another issue I came across, can you take a look ?

File: crates/rattler_conda_types/src/version/mod.rs [hunk 1]
```diff
@@ -506,7 +507,9 @@ impl Version {
                 .with_local_segment_index(segments.len() as u8)
                 .ok_or(VersionExtendError::VersionTooLong)?;
             for segment_iter in self.local_segments() {
-                for component in segment_iter.components().cloned() {
+                // Skip the implicit default `0` for the same reason
+                let implicit_default = usize::from(segment_iter.has_implicit_default());
+                for component in segment_iter.components().skip(implicit_default).cloned() {
```
Comment (baszalmstra) [inline crates/rattler_conda_types/src/version/mod.rs]: Is this change needed?

File: crates/rattler_conda_types/src/version/mod.rs [hunk 2]
```diff
@@ -459,10 +459,11 @@ impl Version {
                 flags = flags.with_has_epoch(true);
             }
 
-            // Copy the segments
+            // Copy the segments. We skip the implicit default `0` component
             for segment_iter in self.segments() {
                 segments.push(segment_iter.segment);
-                for component in segment_iter.components() {
+                let implicit_default = usize::from(segment_iter.has_implicit_default());
+                for component in segment_iter.components().skip(implicit_default) {
```
Comment (baszalmstra) [inline crates/rattler_conda_types/src/version/mod.rs]: Is this needed?

Comment (ritankarsaha) [reply crates/rattler_conda_types/src/version/mod.rs]: Ahh @baszalmstra these two hunks are fixing a separate bug (implicit default 0 being duplicated in strip_local()/extend_to_length())
Coupled them here, sorry should have created another issue to track this, they were loosely related to Versions and stuff spo thought of handling it here as it is a very small change.

Should I create a separate issue for this to track this and make a PR for that @baszalmstra ? For now I am removing these changes, updating as per your reviews and fixing the CI, if this change is needed, lemme know, we can either include it here updating the issue a bit, because both of them are related to Version(very small changes in this one) or we can create a separate issue and track it accordingly.

Comment (baszalmstra) [reply crates/rattler_conda_types/src/version/mod.rs]: Yes split them up please.

Comment (ritankarsaha) [reply crates/rattler_conda_types/src/version/mod.rs]: @baszalmstra got it sure !

Comment (ritankarsaha) [reply crates/rattler_conda_types/src/version/mod.rs]: removed it and will add in a future PR @baszalmstra

File: crates/rattler_conda_types/src/version/mod.rs (hunk 1 above)
Comment (ritankarsaha) [reply crates/rattler_conda_types/src/version/mod.rs]: removed it and will add in a future PR @baszalmstra

**Comment by ritankarsaha** [comment]
@baszalmstra ready for review !!

**Comment by ritankarsaha** [comment]
@baszalmstra fixed reviews, rebased from main, lemme know if any more updates are required to this

**Comment by ritankarsaha** [comment]
@baszalmstra fixed all portions of this PR, anything else needed from my end ?
