### PR TITLE
Nushell fixes

### LINKED ISSUE #306: Rename `behaviour` to `behavior` and always prefer US spelling
We currently have `PathModificationBehaviour` as a enum in the Rust code. 
IMO we should be consistent with US spelling (behavior).

### PR DESCRIPTION
**Pull request by wolfv**
There is one more fix I need to do.

Closes #306

### CODE REVIEW

File: crates/rattler_shell/src/shell/mod.rs [hunk 1]
```diff
@@ -422,12 +422,22 @@ impl Shell for Fish {
...
 pub struct NuShell;
 
 impl Shell for NuShell {
     fn set_env_var(&self, f: &mut impl Write, env_var: &str, value: &str) -> std::fmt::Result {
+        // escape backslashes for Windows (make them double backslashes)
+        let value = if cfg!(windows) {
+            escape_backslashes(value)
+        } else {
+            value.to_string()
+        };
```
Comment (baszalmstra) [inline crates/rattler_shell/src/shell/mod.rs:440]: Dont you always want to escape these? Its not windows specific but more how nushell interprets a string right?

**Review by baszalmstra — APPROVED** [review]
