### PR TITLE
fix: py-rattler: standardize exception names to '*Error' suffix and update docs

### LINKED ISSUE #1959: Inconsistencies between traceback and class names for exception types
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I noticed this strange inconsistency. `rattler.exceptions` are mostly `*Error` names:

```python
>>> dir(rattler.exceptions)
['ActivationError', 'CacheDirError', 'ConvertSubdirError', 'DetectVirtualPackageError', 'EnvironmentCreationError', 'ExtractError', 'FetchRepoDataError', 'GatewayError', 'InvalidChannelError', 'InvalidMatchSpecError', 'InvalidPackageNameError', 'InvalidUrlError', 'InvalidVersionError', 'IoError', 'LinkError', 'ParseArchError', 'ParsePlatformError', 'SolverError', 'TransactionError', 'ValidatePackageRecordsException', 'VersionBumpError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
```

However, in tracebacks, they are suffixed with `*Exception`:

```python
>>> raise rattler.exceptions.InvalidVersionError("1.2.3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
exceptions.InvalidVersionException: 1.2.3
```

That's a bit confusing DX.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ayushman1210**
**Description**
I standardized the exception type names exposed by the Python bindings so tracebacks and the public API are consistent.

**Problem:** 
The Rust glue layer generated Python exceptions with an *Exception suffix while the public Python API and docs use *Error. This caused confusing tracebacks (e.g., InvalidVersionException vs InvalidVersionError).
Change: Renamed generated Python exceptions to use the *Error suffix and updated Python references and doctests to match.
Replaced generated exception names and From<PyRattlerError> mappings in error.rs.
Updated lib.rs to register the new *Error types.
Updated Python shim and docs in exceptions.py and doctests across py-rattler/rattler/*.

**Files changed (high level):**
error.rs
lib.rs
exceptions.py
Doctest updates: match_spec.py, version.py, package_record.py

**Fixes #1959**

How Has This Been Tested?
Steps I ran locally to validate the change:

``````
# ensure submodules (libsolv) are available
git submodule update --init

# format changed Rust files
pixi run cargo-fmt

# quick compile check
pixi run check

# started lint and test runs (may be long-running)
pixi run cargo-clippy            # started locally
pixi run test                   # started locally (recommend CI to run full matrix)

````````
Repro steps for reviewers:

- Checkout this branch.
- Run git submodule update --init.
- Run pixi run check — confirm successful build.
- Optionally run pixi run cargo-clippy and pixi run test in CI or locally.

Notes about validation:
- pixi run check completed successfully after initializing submodules.
- pixi run cargo-clippy and the full test run were started locally (these are long-running); please rely on CI for the full matrix.

AI Disclosure
 This PR contains AI-generated content.
 I have tested any AI-generated content in my PR.
 I take responsibility for any AI-generated content in my PR.
Tools: GitHub Copilot (GPT-5 mini)

Checklist:

-  I have performed a self-review of my own code
-  I have made corresponding changes to the documentation / doctests

If you prefer zero breakage for downstream code that referenced the old generated symbols directly, I can add lightweight backward-compatible aliases in lib.rs that map the old *Exception names to the new *Error types (recommended only if we want to avoid forcing downstream changes). Would you like me to add those aliases?

### CODE REVIEW

**Comment by baszalmstra** [comment]
Can you explain what was wrong with the previous code? Why, if you raised `FooBarError` did the traceback show `FooBarException`?

Your PR also seems to remove a bunch of exceptions bound to python? Why?

Also, please use the formatting from the PR template.

**Comment by ayushman1210** [comment]
@baszalmstra 
Problem: The Rust exception generation layer was creating Python exception types with an *Exception suffix internally (e.g., InvalidVersionException), but these were being re-exported from the Python bindings with *Error names (e.g., InvalidVersionError). When users raised these exceptions, Python's traceback displayed the actual internal class name (*Exception), not the imported alias (*Error), creating a confusing mismatch

**Why the traceback mismatch occurred:**
PyO3's create_exception! macro generates a class with a fixed internal __name__. Even though we aliased them as *Error in Python, the actual class object retained the *Exception name

```
>>> raise rattler.exceptions.InvalidVersionError("1.2.3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
InvalidVersionException: 1.2.3  # ← Shows internal name, confusing users
```
Regarding "Removed Exceptions"Nothing was removed — all exceptions were renamed:

- Before: create_exception!(exceptions, InvalidVersionException, PyException);
- After: create_exception!(exceptions, InvalidVersionError, PyException);

The exceptions still exist and are bound to Python via m.add() calls in lib.rs. They just now have the correct *Error name so tracebacks match the imported name.

**Solution**
Directly renamed exception types in the create_exception! macro calls from *Exception to *Error. This ensures a 1:1 correspondence between:

- The name users import: from rattler.exceptions import InvalidVersionError
- The name shown in tracebacks: InvalidVersionError: <message>


This aligns with how other major Rust↔Python projects (Pydantic, Polars, orjson) handle exceptions—using a single canonical name rather than internal/external name mismatches.f

File: py-rattler/src/error.rs [hunk 1]
```diff
@@ -204,41 +190,20 @@ impl From<PyRattlerError> for PyErr {
...
-create_exception!(exceptions, InstallerException, PyException);
-create_exception!(
-    exceptions,
-    ParseExplicitEnvironmentSpecException,
-    PyException
-);
-create_exception!(exceptions, ValidatePackageRecordsException, PyException);
-create_exception!(exceptions, AuthenticationStorageException, PyException);
-create_exception!(exceptions, ShellException, PyException);
-create_exception!(exceptions, InvalidHeaderNameException, PyException);
```
Comment (baszalmstra) [inline py-rattler/src/error.rs:243]: These are all removed. Why?

**Comment by baszalmstra** [comment]
Btw @ayushman1210, please use your own words. Your comment is clearly LLM-generated. You are violating our AI_POLICY.

File: py-rattler/src/error.rs (hunk 1 above)
Comment (ayushman1210) [reply py-rattler/src/error.rs:243]: I just moved them all into a new  src/exceptions.rs file . I did this to avoid naming collisions between the internal Rust error types and the Python exception classes, which was causing some compilation issues. I also took the opportunity to rename them from *Exception to *Error to follow standard Python naming conventions. They are still being exported and can be caught individually again

**Comment by ayushman1210** [comment]
hey @baszalmstra please review the updated pr 
thanks !!

**Comment by ayushman1210** [comment]
hey @baszalmstra please review this pr when you have some free time if anything else needed please let me know 
thanks !!

**Comment by baszalmstra** [comment]
No need to double-ping. I'll get to it when I get to it.

File: py-rattler/src/error.rs [hunk 2]
```diff
@@ -108,137 +108,110 @@ impl From<PyRattlerError> for PyErr {
...
-create_exception!(exceptions, InvalidHeaderValueError, PyException);
+// No exception definitions here, they are in exceptions.rs
```
Comment (baszalmstra) [inline py-rattler/src/error.rs]:
```suggestion
```
