### PR TITLE
fix: avoid access denied on Windows when concurrent tasks persist repodata to the same cache path

### LINKED ISSUE #1952: [BUG] rattler_repodata_gateway access denied when persisting temporary repodata.json
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I encountered this bug when dealing with a different one involving channel parsing but the issue is when fetching repodata.json for the same channel concurrently through Gateway::query, if the server doesn't return any caching headers, all the attempts will try to write the repodata.json file.  

The problem is that right after persisting the temporary repodata.json file, the lock on the `<cache_key>.json` file is released and a SparseRepoData instance is created.  The SparseRepoData opens the `<cache key>.json` file with memmap2 while other threads/processes are now trying to persist their temporary repodata.json files to the same location causing an access denied on windows.

### Additional Context

Here's an example with an Artifactory server demonstrating both bugs.  Because the way the channel parsing currently works, it treats both of the `Channels` in `channels` as different even though they resolve to the same thing.

One has `name: Some("conda_example")` while the other has `name: Some("artifactory/api/conda/conda_example")`.  In this example and in my use-case it was because of this channel bug that I passed duplicate channels into the query but the above access denied issue would also occur if multiple processes were making the same requests.

```
    let cur_dir = std::env::current_dir()?;
    let cache_dir = cur_dir.join("cache");
    let gateway = rattler_repodata_gateway::Gateway::builder()
        .with_cache_dir(cache_dir)
        .finish();
    let channel_config = ChannelConfig {
        channel_alias: Url::from_str("https://example.jfrog.io/artifactory/api/conda/")?,
        root_dir: cur_dir,
    };
    let channels = vec![
        Channel::from_name("conda_example", &channel_config),
        Channel::from_str("https://example.jfrog.io/artifactory/api/conda/conda_example", &channel_config)?,
    ];
    let res = gateway.query(
        channels,
        [Platform::Win64, Platform::NoArch],
        [MatchSpec::from_str("python==3.14", Lenient)?],
    ).recursive(true).await?;
```

### PR DESCRIPTION
**Pull request by devvaansh**
### Description

This PR addresses an "Access Denied" (OS error 5) issue on Windows that occurs when multiple tasks attempt to fetch the same channel concurrently while the server returns no caching headers.
Fix:
Before persisting the freshly downloaded file, the existing cache file is renamed aside to a uniquely-named path (<key>.json.deprecated.<nanos>). Windows permits renaming an open/mapped file, allowing the new file to be written to the canonical location without conflict. Stale deprecated files are cleaned up eagerly on subsequent fetches.

Fixes #1952 

### How Has This Been Tested?

I have added a regression test: test_concurrent_fetch_no_cache_headers.
Method: Spawns four concurrent fetch_repo_data calls against a mock server that returns no caching headers.
Verification: Asserts that all calls succeed without "Access Denied" errors and verifies that no leftover .deprecated files remain in the cache directory after completion.

### AI Disclosure

- [X] This PR contains AI-generated content.
  - [x] I have tested any AI-generated content in my PR.
  - [X] I take responsibility for any AI-generated content in my PR.

Tools: Claude

### Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added sufficient tests to cover my changes.

### CODE REVIEW

**Comment by devvaansh** [comment]
@baszalmstra please review

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs [hunk 1]
```diff
@@ -1485,4 +1561,83 @@ mod test {
             "there must have been exactly two requests"
         );
     }
+
+    // Regression test for https://github.com/conda/rattler/issues/1952.
+    // Concurrent fetches for the same uncached channel must all succeed even
+    // though every task tries to persist to the same cache path.
+    #[tracing_test::traced_test]
+    #[tokio::test(flavor = "multi_thread")]
+    pub async fn test_concurrent_fetch_no_cache_headers() {
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: This test doesnt memory map the file right? So doesnit actually test the scenario where the file cannot be deleted?

**Comment by devvaansh** [comment]
Good points will update the test to actually memory map the file ensuring hitting the 'Access Denied' state also move the fallback logic so it only triggers on a PermissionDenied error and moves the stale files into a .trash directory to keep the main cache clean.

Regarding FILE_SHARE_DELETE, I'll check if we can incorporate that into the sharded_repodata loading to make the file more 'movable' even while mapped.

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs (hunk 1 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: added memmap2 to the dev-deps and updated the regression test. It now explicitly mmaps the file and holds it "hostage" while the concurrent fetches run.

**Comment by devvaansh** [comment]
@baszalmstra  here are the Fixes:
Lazy Deprecation: We’re no longer moving files aggressively. The code now tries a direct persist() first. We only pivot to the "trash" logic if Windows actually throws a fit (the Err branch).
The .trash Bin: No more .deprecated files cluttering up the main cache. I’ve implemented trash_dir_for() and move_to_trash(). It keeps the readdir operations snappy and the workspace clean.
Windows-Specific Flags: I wrangled the Windows API and added FILE_SHARE_DELETE using OpenOptionsExt. This should let us delete/rename files even while they're being read, a win for concurrency.

**Comment by devvaansh** [comment]
@baszalmstra  right With FILE_SHARE_DELETE enabled, the lazy deletion / .trash workaround is completely unnecessary, pushed a commit that removes all of that complexity, persist logic is now back to  direct persist() call, which works perfectly even when the file is memory-mapped.

File: crates/rattler_repodata_gateway/Cargo.toml [hunk 2]
```diff
@@ -91,6 +91,7 @@ hex-literal = { workspace = true }
 http = { workspace = true }
 http-cache-semantics = { workspace = true, features = ["serde"] }
 insta = { workspace = true, features = ["yaml"] }
+memmap2 = { workspace = true }
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/Cargo.toml]: Its already a normal dependency.

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs [hunk 3]
```diff
@@ -442,20 +442,55 @@ pub async fn fetch_repo_data(
         reporter.on_download_complete(&response_url, index);
     }
 
-    // Persist the file to its final destination
+    // Persist the file to its final destination.
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: We now have a fix for this so can we revert?

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs [hunk 4]
```diff
@@ -1485,4 +1520,107 @@ mod test {
...
+    // Regression test for https://github.com/conda/rattler/issues/1952.
+    // Concurrent fetches for the same uncached channel must all succeed even
+    // though every task tries to persist to the same cache path.
+    //
+    // The test memory-maps the cache file after the first fetch so that on
+    // Windows the file would normally cause "access denied". Opening with
+    // FILE_SHARE_DELETE (see `open_for_mmap`) allows the persist to succeed.
+    #[tracing_test::traced_test]
+    #[tokio::test(flavor = "multi_thread")]
+    pub async fn test_concurrent_fetch_no_cache_headers() {
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: Seems like this can be drastically simplified and more targeted. Just use SpareRepodata and try to delete the file.

File: crates/rattler_repodata_gateway/src/sparse/mod.rs [hunk 5]
```diff
@@ -138,6 +139,28 @@ self_cell::self_cell!(
...
+/// `FILE_SHARE_DELETE` so that another process/thread can rename or delete
+/// the file while it is still mapped.
+#[cfg(windows)]
+fn open_for_mmap(path: &Path) -> io::Result<std::fs::File> {
+    use std::os::windows::fs::OpenOptionsExt;
+    // FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE
+    const SHARE_ALL: u32 = 0x01 | 0x02 | 0x04;
+    std::fs::OpenOptions::new()
+        .read(true)
+        .share_mode(SHARE_ALL)
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/sparse/mod.rs]: Only the share mode is different for this function, please try keep the difference as small as possible.

File: crates/rattler_repodata_gateway/src/utils/body.rs [hunk 6]
```diff
@@ -43,6 +43,7 @@ pin_project! {
 }
 
 impl<S, E> BytesCollect<S, E> {
+    #[allow(dead_code)]
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/utils/body.rs]: We talked about this in your last Pr.

File: crates/rattler_repodata_gateway/Cargo.toml (hunk 2 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/Cargo.toml]: Removed memmap2

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs (hunk 3 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: Reverted. Switched back to a simple direct call

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs (hunk 4 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: Replaced complex concurrent test using SparseRepoData and a direct file deletion check as suggested

File: crates/rattler_repodata_gateway/src/sparse/mod.rs (hunk 5 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/sparse/mod.rs]: Merged the logic into a single function using internal #[cfg] blocks

File: crates/rattler_repodata_gateway/src/utils/body.rs (hunk 6 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/utils/body.rs]: My bad, will take care for future

**Comment by devvaansh** [comment]
@baszalmstra  adressed all your reviews

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs [hunk 7]
```diff
@@ -1486,3 +1486,43 @@ mod test {
...
 }
+
+/// Regression test for <https://github.com/conda/rattler/issues/1952>.
+///
+/// On Windows, memory-mapped files cannot be deleted unless they were opened
+/// with `FILE_SHARE_DELETE`. [`SparseRepoData::from_file`] uses `open_for_mmap`
+/// which sets that flag. This test verifies that a file opened via
+/// `SparseRepoData` can be deleted (or replaced) while the mapping is alive.
+#[cfg(feature = "sparse")]
+#[cfg(any(unix, windows))]
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: this is a bit superfluous

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs [hunk 8]
```diff
@@ -1486,3 +1486,43 @@ mod test {
...
+#[cfg(test)]
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: Why not just add this to the test module instead of creating a seperate one with one test??

File: crates/rattler_repodata_gateway/src/sparse/mod.rs [hunk 9]
```diff
@@ -12,6 +12,7 @@ use std::{
 };
 
 use bytes::Bytes;
+#[cfg(not(windows))]
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/sparse/mod.rs]: Instead of importing with a cfg just use it inline.

File: crates/rattler_repodata_gateway/src/sparse/mod.rs [hunk 10]
```diff
@@ -138,6 +139,30 @@ self_cell::self_cell!(
     }
 );
 
+/// Opens a file for memory-mapping.
+///
+/// On Windows the file is opened with `FILE_SHARE_DELETE` so that another
+/// process/thread can rename or delete the file while it is still mapped.
+/// On Unix no special flags are needed since unlinking an open file is always
+/// allowed.
+#[cfg(any(unix, windows))]
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/sparse/mod.rs]: This is not needed, you are already doing this inside the function itself.

File: crates/rattler_repodata_gateway/src/sparse/mod.rs [hunk 11]
```diff
@@ -138,6 +139,30 @@ self_cell::self_cell!(
...
+        // FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE
+        const SHARE_ALL: u32 = 0x01 | 0x02 | 0x04;
+        std::fs::OpenOptions::new()
+            .read(true)
+            .share_mode(SHARE_ALL)
+            .open(path)
+    }
+    #[cfg(not(windows))]
+    {
+        fs::File::open(path).map(Into::into)
```
Comment (baszalmstra) [inline crates/rattler_repodata_gateway/src/sparse/mod.rs]:
```suggestion
        fs::File::open(path)
```

**Comment by devvaansh** [comment]
> Before rerequesting a review, please review the code _yourself_. Much of the issues look like mistakes an AI makes.

sorry will take care for next time

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs (hunk 7 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: Removed both. The test is now inside the existing modest block

File: crates/rattler_repodata_gateway/src/fetch/with_cache.rs (hunk 8 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/fetch/with_cache.rs]: Deleted mod share_delete_test entirely. Moved the test into the existing mod test block

File: crates/rattler_repodata_gateway/src/sparse/mod.rs (hunk 9 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/sparse/mod.rs]: Now using fs_err::File::open()and fs_err::read() inline at the two call-sites.

File: crates/rattler_repodata_gateway/src/sparse/mod.rs (hunk 10 above)
Comment (devvaansh) [reply crates/rattler_repodata_gateway/src/sparse/mod.rs]: Eliminated the standalone open_for_mmap function entirely

**Comment by devvaansh** [comment]
@baszalmstra, could you please enable auto-merge again, It seems to have been disabled by my recent commit
