### PR TITLE
fix(virtual_packages): handle invalid chars in LibC family

### LINKED ISSUE #2208: From<LibC> for GenericVirtualPackage can panic if libc.family contains invalid conda package name characters
### What happened?

In [crates/rattler_virtual_packages/src/lib.rs](file:///home/ayushman1210/.gemini/antigravity/scratch/rattler/crates/rattler_virtual_packages/src/lib.rs), the `From<LibC> for GenericVirtualPackage` implementation constructs a [PackageName](file:///home/ayushman1210/.gemini/antigravity/scratch/rattler/crates/path_resolver/src/lib.rs#20-21) directly from `libc.family`:

```rust
impl From<LibC> for GenericVirtualPackage {
    fn from(libc: LibC) -> Self {
        GenericVirtualPackage {
            // TODO: Convert the family to a valid package name. We can simply replace invalid
            // characters.
            name: format!("__{}", libc.family.to_lowercase())
                .try_into()
                .unwrap(),
            version: libc.version,
            build_string: "0".into(),
        }
    }
}
```

Because `libc.family` is arbitrary text pulled from the OS, if it happens to contain characters that are invalid for conda package names (like spaces or special symbols), the `try_into()` string parsing will fail and the `.unwrap()` will panic, crashing the application.

As the `TODO` comment above the line notes, the family string should be sanitized (e.g., replacing invalid characters with `_`) before converting it into a package name to prevent this panic.

### Additional Context

This was discovered while auditing the codebase for open `TODO` / `FIXME` comments.

### PR DESCRIPTION
**Pull request by ayushman1210**
### Description

`From<LibC> for GenericVirtualPackage` can panic on invalid characters during package name conversion, as there was an unhandled `unwrap()` on string parsing.
This PR fixes the panic by removing non-alphanumeric characters, replacing them with `_`.

Because `libc.family` is arbitrary text pulled from the OS, if it contains characters that are invalid for conda package names (like spaces or parentheses), the string parsing would fail and `.unwrap()` would panic, completely crashing the application. 

This correctly implements the `TODO` comment that noted the family string should be sanitized (e.g., replacing invalid characters) before converting it into a package name to prevent this panic.

Fixes #2208 

### How Has This Been Tested?

Added 1 unit test in [crates/rattler_virtual_packages/src/lib.rs](file:///home/ayushman1210/.gemini/antigravity/scratch/rattler/crates/rattler_virtual_packages/src/lib.rs) to verify that `libc.family` strings with parentheses and spaces are properly sanitized into package names.

```bash
cargo test -p rattler_virtual_packages
```

### AI Disclosure

- [x] This PR contains AI-generated content. (The code changes and tests were drafted with the help of an AI assistant)
  - [x] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.
Tools: Google Gemini 

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added sufficient tests to cover my changes.

### CODE REVIEW

**Comment by ayushman1210** [comment]
hey @baszalmstra please review this pr when you have some free time and  if any changes needed please let me know 
thanks !!

**Comment by ayushman1210** [comment]
hey @baszalmstra please review this pr when you have some free time thanks !!

**Comment by ayushman1210** [comment]
hey @baszalmstra please review this pr when you have some time !!

File: crates/rattler_virtual_packages/src/lib.rs [hunk 1]
```diff
@@ -510,9 +510,15 @@ impl From<LibC> for GenericVirtualPackage {
         GenericVirtualPackage {
             // TODO: Convert the family to a valid package name. We can simply replace invalid
```
Comment (baszalmstra) [inline crates/rattler_virtual_packages/src/lib.rs]: We can remove this can we not?

Comment (ayushman1210) [reply crates/rattler_virtual_packages/src/lib.rs]: remove obsolete TODO comment about converting LibC family name
